Feat/battle board poc
aresrpg/aresrpg-dapp pull request #153
Opened 2024-09-18 16:32 UTC by etienne-85

- board POC 
- much cleaner game_terrain code

2024-10-01 07:24 UTC, Sceat requested changes

2024-10-01 07:24 UTC, Sceat commented on src/core/utils/terrain/world_utils.js
> +  board.origin.y++ // TODO: check where comes the issue
Since you are creating the board object, why assigning value just after ?

2024-10-01 07:24 UTC, Sceat commented on src/core/modules/game_terrain.js
> +const ON_THE_FLY_GEN = true // when disabled patches will be baked in advance
those variables do not look productio ready

2024-10-01 07:24 UTC, Sceat commented on src/core/modules/game_terrain.js
> +    // )
what's on the fly gen? should it stay there in the code commented?

2024-10-01 07:24 UTC, Sceat commented on src/core/utils/terrain/world_settings.js
> +// TODO remove hardcoding and retrieve dynamic value from world
```suggestion
// TODO: remove hardcoding and retrieve dynamic value from world
```

https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight

2024-10-02 08:36 UTC, etienne-85 commented on src/core/modules/game_terrain.js
> +const ON_THE_FLY_GEN = true // when disabled patches will be baked in advance
no this is just a POC, but it was needed for disabling board display until we get full integration

2024-10-02 08:36 UTC, etienne-85 commented on src/core/utils/terrain/world_utils.js
> +const blocks_cache_radius = Math.pow(2, 3) // 8 blocks
Will use 2 ** 3 then. This is a slightly more convenient way to adjust cache size, by using powers of 2, you can simply increment by one to double the cache size or decrement by one to halve it (downside being, code is less human-readable)

2024-10-02 08:36 UTC, etienne-85 commented on src/core/utils/terrain/world_utils.js
> +const blocks_cache_min_batch_size = Math.pow(2 * blocks_cache_radius, 2) / 4 // 16*16/4 = 256/4 = 64 blocks batch
The main reason it was written this way is to ensure that the batch size scales proportionally with the cache radius (thereby minimizing the number of variables to adjust). This also highlight relationship between batch and cache size, with the batch size being easily defined as half, a quarter, or 1/8 of the cache size.

2024-10-02 08:45 UTC, etienne-85 commented on src/core/modules/game_terrain.js
> +    // )
I kept it just as a reminder but this can be removed. Patch are computed on the fly.. in opposite to being done all at once.

2024-10-02 08:48 UTC, etienne-85 commented on src/core/utils/terrain/world_utils.js
> +    let req
Shouldn't be necessay to update code as it is meant to be removed with world builtin precache support coming in next release

2024-10-07 07:46 UTC, Sceat commented on src/core/modules/game_terrain.js
> +    // )
better to not leave comments that could be confusing unless currently useful

2024-10-21 13:15 UTC, closed without merging