Feat/day night cycle
aresrpg/aresrpg-dapp pull request #49
Opened 2024-03-24 13:11 UTC by piellardj

This PR adds a dynamic day/night cycle:
- dynamic skybox with nice sunsets, rotating night sky etc.
- dynamic fog color
- dynamic shadows

![image](https://github.com/aresrpg/aresrpg-dapp/assets/22922087/357aefef-df6d-4465-836a-2c552971e350)

2024-03-24 22:08 UTC, Sceat requested changes
The cycle look awesome !

A quick precision on the `aiter` and reducers pattern, `aiter` stands for async-iterator and is an ecma proposal to provide async sequential iteration in nodejs. We are using it to isolate asynchrone events and actions/packet feed. Used with a reducer it allows us to have separation of concerns in a private scope.

```js
await aiter(async_iterator).forEach(console.log)
```

In AresRPG we are using it with the main events and packets to derivate actions from the reduced state.

```js
// abortable just catch the abort errors of the AbortSignal
aiter(abortable(on(events, 'STATE_UPDATED')))
	.reduce(last_name, ([{ name }]) => {
		if(last_name !== name) {
			// the name changed so do something
		}

		return name
	})
```

This pattern allows us to detect change in a local scope and execute side effects reacting to it.

In the case of the Sky settings, to follow the core principle, it's correct to emit an event if you need a direct action, and it's incorrect to emit an event to change a value, if you need to share variables between modules you need to update the game state (by `dispatching` an action, which has to be caught in a `reducer` to mutate the state)
Then you can react to that state change in a `aiter` loop. In your case you could have a simple `action/sky_settings` which is an object containing any variables you need to share between modules, and you would reduce that by comparing each property

```js
aiter(abortable(on(events, 'STATE_UPDATED')))
	.reduce(last_settings, ([state]) => {
		if(last_settings.sky_color !== state.sky.sky_color) {
			// do something
		}
		return name
	})
```

in case you need to react to those change outside the reducer, you can do something like this


```js
const sky_settings = { } // this is a module scoped variable

aiter(abortable(on(events, 'STATE_UPDATED')))
	.forEach(([state]) => {
		if(sky_settings.sky_color !== state.sky.sky_color) sky_settings.sky_color = state.sky.sky_color
	})

aiter(// each seconds).forEach(do_something)
```

There is another pattern which is handy and use the combination of multiple sources

```js
aiter(combine(
	setInterval(day_time_step, { i_am_interval: 42 }, { signal }),
	on(events, 'event')
)).reduce(last, value => {
	if(value.i_am_interval) // this is the interval trigger
	else // this is the even
})
```

It would make more sense to only use the `game_sky` for anything related to the cycle and only use `game_lights` for something more specific to lightning (if required)

2024-03-24 22:08 UTC, Sceat commented on src/core/modules/game_lights.js
> +  let daytimePaused = false
please use snake_case everywhere for the dApp

2024-03-24 22:08 UTC, Sceat commented on src/core/modules/game_lights.js
> +      let day_time = DAY_DURATION * get_state().settings.sky.value // Track the time of day as a value between 0 and DAY_DURATION
using the state that way is unreliable, you should at least wait for an `events.once('STATE_UPDATED')` to be sure the state actually exists. Also note that this is no different from a constant because you'll only get the initial value

2024-03-24 22:08 UTC, Sceat commented on src/core/modules/game_lights.js
> +      events.on('SKY_CYCLE_PAUSED', paused => (daytimePaused = paused))
as stated in the review, passing data through events isn't comfortable, it should be private to the module or go through the state, there is an exception to that when we truely need the up to date data in the `tick` function but not the case here

2024-03-24 22:08 UTC, Sceat commented on src/types.d.ts
> +      SKY_AMBIENTLIGHT_CHANGED: { color: Color; intensity: number }
those can be compacted in a single `SKY_SETTINGS` event which contains an object with all properties which are needed for inter_module communication, but remember it's mainly for direct execution, if it's about updating the state it should be an `action/`

2024-03-24 22:31 UTC, piellardj commented on src/core/modules/game_lights.js
> +  let daytimePaused = false
Done in 4c3224a95634c8a86b35ad3d11408d9957c0cbe4.
I tried adding a linting rule to enforce snake_case, however in the project the linter finds 78 variables that don't follow snake_casing. Add a rule for this would be a PR on its own I think.

2024-03-27 16:06 UTC, piellardj commented on src/types.d.ts
> +      SKY_AMBIENTLIGHT_CHANGED: { color: Color; intensity: number }
Fixed in next commits

2024-03-27 16:06 UTC, piellardj commented on src/core/modules/game_lights.js
> +      events.on('SKY_CYCLE_PAUSED', paused => (daytimePaused = paused))
Fixed in next commits

2024-03-27 16:06 UTC, piellardj commented on src/core/modules/game_lights.js
> +      let day_time = DAY_DURATION * get_state().settings.sky.value // Track the time of day as a value between 0 and DAY_DURATION
Fixed in next commits

2024-03-27 16:16 UTC, Sceat approved these changes

2024-03-27 17:45 UTC, merged